services:
  app:
    container_name: mlb-container
    image: fonssi29/mlb-portal:dev
    ports:
      - "8443:8443"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mlb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

      CLOUDINARY_CLOUD_NAME: dexuwucsw
      CLOUDINARY_API_KEY: 353971379779258
      CLOUDINARY_API_SECRET: l4WceL7n4TWUIOECrqpsiDHqzvc

      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: mlbportal29@gmail.com
      SPRING_MAIL_PASSWORD: wzjmephecegyelui
      
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: true
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: true
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_CONNECTIONTIMEOUT: 10000
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_TIMEOUT: 10000
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_WRITETIMEOUT: 10000
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: mysql-container
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mlb
    volumes:
      - db_data_dev:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  db_data_dev: