name: CD Dispatch (Manual Build)

on:
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: fonssi29/mlb-portal

jobs:
  checkout-code:
    name: Checkout Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commit || github.event.inputs.branch }}

  build-backend:
    name: Backend Build
    runs-on: ubuntu-latest
    needs: checkout-code
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commit || github.event.inputs.branch }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Backend Package
        run: mvn -q -B clean package -DskipTests
        working-directory: ./backend

  build-frontend:
    name: Frontend Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Node.js 22 Configuration
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      # Install Angular Dependencies
      - name: Install Dependencias
        run: npm install
        working-directory: ./frontend

      - name: Compile Frontend
        run: npm run build -- --configuration production
        working-directory: ./frontend

  docker-build-push:
    name: Docker Build & Push
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    outputs:
      tag: ${{ steps.compute.outputs.tag }}
    env:
      SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
      SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commit || github.event.inputs.branch }}

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Restore keystore from secret
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > backend/src/main/resources/keystore.p12

      - name: Compute Tag
        id: compute
        run: |
          BRANCH=${{ github.event.inputs.branch }}
          COMMIT=${{ github.event.inputs.commit || github.sha }}
          DATE=$(date +'%Y%m%d-%H%M%S')
          echo "tag=${BRANCH}-${DATE}-${COMMIT}" >> $GITHUB_OUTPUT

      - name: Build & Push Docker image
        run: |
          TAG=${{ steps.compute.outputs.tag }}
          docker build -f ./docker/Dockerfile -t $REGISTRY/$IMAGE_NAME:$TAG .
          docker push $REGISTRY/$IMAGE_NAME:$TAG

  publish-compose:
    name: Publish Compose OCI
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commit || github.event.inputs.branch }}

      - name: Publish Compose OCI with dynamic tag
        run: |
          TAG=${{ needs.docker-build-push.outputs.tag }}
          docker compose -f ./docker/docker-compose.yml publish $REGISTRY/$IMAGE_NAME:$TAG --with-env 