name: CD Main (Dev Publish)

on:
  pull_request:
    branches:
      - main

env:
  REGISTRY: docker.io
  IMAGE_NAME: fonssi29/mlb-portal

jobs:
  build-backend:
    name: Backend Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Backend Package
        run: mvn -q -B clean package -DskipTests
        working-directory: ./backend

  build-frontend:
    name: Frontend Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Node.js 22 Configuration
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      # Install Angular Dependencies
      - name: Install Dependencias
        run: npm install
        working-directory: ./frontend

      - name: Compile Frontend
        run: npm run build -- --configuration production
        working-directory: ./frontend

  docker-build-push:
    name: Docker Build & Push
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    env:
      SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
      SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
    steps:
      - uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker image
        run: |
          docker build -f ./docker/Dockerfile -t $REGISTRY/$IMAGE_NAME:dev .
          docker push $REGISTRY/$IMAGE_NAME:dev

  publish-compose:
    name: Publish Compose OCI
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - uses: actions/checkout@v4

      - name: Publish Compose OCI with tag dev
        run: docker compose publish $REGISTRY/$IMAGE_NAME:dev --with-env