name: CD Release (Version & Latest)

on:
  release:
    types: [published]

env:
  REGISTRY: docker.io
  IMAGE_NAME: fonssi29/mlb-portal

jobs:
  build-and-publish-release:
    runs-on: ubuntu-latest
    env:
      SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
      SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      # Backend build
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - run: mvn -q -B clean package -DskipTests
        working-directory: ./backend

      # Frontend build
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm run build -- --configuration production
        working-directory: ./frontend

      # Docker login
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build & push image with version and latest
      - name: Build & Push Docker image
        run: |
          VERSION=${{ github.event.release.tag_name }}
          docker build -t $REGISTRY/$IMAGE_NAME:${VERSION}.0 .
          docker push $REGISTRY/$IMAGE_NAME:${VERSION}.0
          docker tag $REGISTRY/$IMAGE_NAME:${VERSION}.0 $REGISTRY/$IMAGE_NAME:latest
          docker push $REGISTRY/$IMAGE_NAME:latest

      # Publish Compose OCI with version and latest
      - name: Publish Compose OCI
        run: |
          VERSION=${{ github.event.release.tag_name }}
          docker compose publish $REGISTRY/$IMAGE_NAME:${VERSION}
          docker compose publish $REGISTRY/$IMAGE_NAME:latest