name: Basic Quality Control

on:
  push:
    branches:
      - "feature/**"
      - "fix/**"
      - "config/**"
  workflow_dispatch:

env:
  CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
  CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
  CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}

jobs:
  build-backend:
    name: Backend Build BC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Java 22 + GraalVM Configuration
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "graalvm"
          java-version: "22"

      - name: Backend Compile
        run: mvn clean compile
        working-directory: ./backend

  backend-unit-tests:
    name: Backend Unit Tests
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Run Unit Tests
        run: mvn test -Dsurefire.excludes="**/integration/**,**/e2e/**"
        working-directory: ./backend

  build-frontend:
    name: Frontend Build BC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Node.js 22 Configuration
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      # Install Angular Dependencies
      - name: Install Dependencias
        run: npm install
        working-directory: ./frontend

      - name: Compile Frontend
        run: npm run build -- --configuration production
        working-directory: ./frontend

  frontend-unit-tests:
    name: Frontend Unit Tests
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install Dependencies
        run: npm install
        working-directory: ./frontend
      - name: Run Unit Tests
        run: npm run test:unit
        working-directory: ./frontend
